# Generated by Django 5.0.4 on 2024-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_carasteristique2_sous_text1_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
